### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelections' of undefined

### ISSUE THREAD

**Issue by danielosoki** [andersennl/case-switch#8] opened 2018-07-17 07:22 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [case-switch](https://github.com/andersennl/case-switch) package 2.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelections' of undefined

```
At C:\Users\Hali\.atom\packages\case-switch\lib\selector.coffee:18

TypeError: Cannot read property 'getSelections' of undefined
    at Selector.module.exports.Selector.convertToCamel (/packages/case-switch/lib/selector.coffee:18:5)
    at Object.convertToCamelCase (/packages/case-switch/lib/case-switch.coffee:20:20)
    at /packages/case-switch/lib/case-switch.coffee:12:82)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.2/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.28.2/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.28.2/resources/app/src/atom-environment.js:1347:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.28.2/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -1:18.7.0 pane:split-right-and-copy-active-item (img.welcome-img)
     -1:02.0 bracket-matcher:go-to-matching-bracket (atom-pane.pane.active)
     -0:52.3.0 window:increase-font-size (atom-pane.pane.active)
     -0:39.4.0 editor:select-to-beginning-of-word (atom-pane.pane.active)
     -0:23.1.0 teletype:share-portal (atom-pane.pane.active)
     -0:11 case-switch:convert-to-camel-case (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-bitcoin 0.6.0 
atom-clock 0.1.16 
atom-crypto-bar 0.7.0 
atom-eclipse-syntax 0.0.6 
atom-netconf 1.6.1 
autumn-highlighter-syntax 1.13.0 
bitcoin-status-bar 0.2.0 
brightpoint 0.3.1 
case-switch 2.2.4 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.5 
floobits 0.32.12 
hey-pane 1.1.0 
Hydrogen 2.5.1 
jackhammer-syntax 1.1.0 
join-plus 0.4.0 
rabbitvcs-svn 0.6.0 
scroll-through-time 0.3.0 
styri-syntax 0.2.0 
tab-switcher 1.5.6 
teletype 0.13.3 
theme-switch 0.6.0 
zentabs 0.8.9 
```

**Comment by andersennl** [comment] 2018-07-17 07:28
Hi @danielosoki, it's possible that the issue is related to an update of Atom. This packages wasn't updated in a while and is currently unmaintained, as I've stopped using Atom. I'll hence close the issue for now - feel free to open a pull request if you're able to fix the issue.

**Closed as completed by andersennl** 2018-07-17 07:28 UTC
